# Generated by Django 4.0.3 on 2022-04-21 11:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('89381eb3-5e83-4c56-bc21-56c1654fe2f1'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='book_images/')),
                ('course', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('sem', models.CharField(max_length=2)),
                ('subject', models.CharField(max_length=50)),
                ('seller', models.CharField(max_length=50)),
            ],
        ),
    ]
