# Generated by Django 4.0.3 on 2022-04-22 05:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1e70aae8-43bc-4869-b5bb-1b3e248153e1'), editable=False, primary_key=True, serialize=False),
        ),
    ]
